[build]
command = ""
publish = "."

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[functions."sendFeedbackEmails-scheduled"]
schedule = "*/5 * * * *"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/feedback"
  to = "/feedback.html"
  status = 200

[[redirects]]
  from = "/feedback/"
  to = "/feedback.html"
  status = 200
